#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK IF THE APP CAN BE MOVED WITH THESE ARGS
#=================================================

if [ $change_domain -eq 1 ]
then
	# Check if .well-known is available for the new domain.
	if is_url_handled --domain="$new_domain" --path="/.well-known/caldav" || is_url_handled --domain="$new_domain" --path="/.well-known/carddav"
	then
		ynh_die "Another app already uses the domain $new_domain to serve a calDAV/cardDAV feature. Please use another domain."
	fi
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE CONFIGURATION
#=================================================
ynh_script_progression "Updating $app configuration..."

ynh_backup_if_checksum_is_different "$install_dir/config/baikal.yaml"

ynh_replace --match="base_uri: '$old_path'" --replace="base_uri: '$new_path'" --file="$install_dir/config/baikal.yaml"

ynh_store_file_checksum "$install_dir/config/baikal.yaml"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
