#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep="config Specific"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="AbstractExternalAuth.php" --destination="$install_dir/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php"
ynh_config_add --template="LDAPUserBindAuth.php" --destination="$install_dir/Core/Frameworks/Baikal/Core/LDAPUserBindAuth.php"
chmod -R 640 "$install_dir"/Core/Frameworks/Baikal/Core/*
chown -R $app:www-data "$install_dir"/Core/Frameworks/Baikal/Core/*
ynh_exec_as_app mkdir "$install_dir/bin"
cp $YNH_APP_BASEDIR/conf/upgrade.sh "$install_dir/bin/"
chmod -R 750 "$install_dir/bin"
chown -R $app:www-data "$install_dir/bin"

touch "/var/log/nginx/${domain}-error.log"

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex='"PHP message: user \(name stripped-out\) authentication failure for Baikal" while reading response header from upstream, client: <HOST>'

#=================================================
# UPGRADE BAIKAL CONFIGURATION
#=================================================
ynh_script_progression "Upgrading the configuration file..."

path=${path%/}
ynh_config_add --template="baikal.yaml" --destination="$install_dir/config/baikal.yaml"

chmod 640 "$install_dir/config/baikal.yaml"
chown $app:$app "$install_dir/config/baikal.yaml"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
